### ISSUE TITLE
Pantalla Inicio sesión

### ISSUE THREAD

**Issue by fincamd** [SmallDreamDev/small-dream-cliente#11]

**Comment by AdrianPerezManso** [comment]
Propongo esto para el inicio de sesión: 
![inicio_sesion](https://user-images.githubusercontent.com/56108486/90335152-faad2980-dfd2-11ea-922c-9f4d0afe831d.PNG)

Ya me dices que te parece @fincamd

**Comment by fincamd** [comment]
Preparado en 6eb7ffaa5d734a69480c55694dc5f3738e489702
