### ISSUE TITLE
Pantalla formularios

### ISSUE THREAD

**Issue by fincamd** [SmallDreamDev/small-dream-cliente#13]
- [x] Cliente
- [x] Actividad
- [x] Monitor
- [x] Programa

**Comment by AdrianPerezManso** [comment]
Dejo por aquí mis prototipos para crear las entidades.

Primero una pantalla con el formulario estándar: 
![crear_entidad](https://user-images.githubusercontent.com/56108486/90337302-e58bc700-dfe1-11ea-8d84-de384ed907e8.PNG)


La pantalla de confirmación:
![confirmar_entidad](https://user-images.githubusercontent.com/56108486/90337310-f2a8b600-dfe1-11ea-82a3-6a0c2d2a3d5d.PNG)

**Comment by fincamd** [comment]
Preparado en 6eb7ffaa5d734a69480c55694dc5f3738e489702
