### ISSUE TITLE
Ficha de cliente: mostrar actividades en las que está apuntado

### ISSUE THREAD

**Issue by AdrianPerezManso** [SmallDreamDev/small-dream-cliente#19]
Hablado con el PO. La idea es que cuando se acceda a la ficha de alguno de los clientes, además de toda la información relativa a él, apareciera lista con las actividades a las que se ha apuntado, y de alguna manerar mostrar si ha asistido a ellas o no.

Ejemplo:

### Luis González

* Edad: 11
* Contacto: 555555

Actividades:
* Informática: [x] [x] [ ] [ ]
* Manga: [ ] [ ]

De esta manera, se ve de manera visual los talleres apuntados, talleres asistidos y talleres no asistidos.
Ya me dices, @fincamd

**Comment by fincamd** [comment]
Alguna cosa así tenía en mente...  Tienes razón, es muy visual la forma de ver los eventos que se relacionan con el cliente. Puede funcionar!

**Comment by AdrianPerezManso** [comment]
Se ha acordado hacer otra vista en la que se maneje toda la asistencia pertinente a la actividad. A esta vista se accederá a través de la vista de detalles del propio taller. Aquí se podrá ver el nombre de la actividad del taller y una lista con los clientes apuntados, los cuales tendrán asociados un estado de asistencia (Asistido, No asistido).

**Comment by AdrianPerezManso** [comment]
Ya existen las dos vistas correspondiente a la asistencia de los clientes a las programaciones.
