### ISSUE TITLE
Rediseño BD: Talleres con campos erróneos

### ISSUE THREAD

**Issue by AdrianPerezManso** [SmallDreamDev/small-dream-cliente#20]
Echando un vistazo [al modelo desarrollado de la base de datos](https://github.com/SmallDreamDev/small-dream-servidor/blob/master/docs/modelos/bdatos/bdatos_desarrollado.jpg), me he dado cuenta de que los campos `fecha` y `plazas` no deberían formar parte de `Talleres`. 

Me explico: `Taller` es una relación-entidad que surje entre `Actividad` y `Monitor`, es decir, representa un vínculo entre quíen imparte qué, por lo que debería guardar cuál es el método de pago (si es por niño o por hora) por el cual cobra el monitor por dar esa actividad, por ejemplo. 

Sin embargo, el día en que se realice una actividad y el número de plazas están totalmente desligado a esta relación (`Taller`), ya que dependerían también de la entidad `Horario`. 

Pongo un ejemplo: si Adrián Pérez imparte Apps móviles se guarda un `Taller` en el que figure ese vínculo y el modo de pago, sin embargo ese `Taller` se puede impartir el sábado 12 de septiembre de 11.00 a 12.00 y ese mismo domingo de 13.00 a 14.00, por lo que si ponemos un campo `fecha` en `Taller` estamos limitando esa libertad de ponerla en el día que sea, además de que el campo `fecha` de la entidad `Programa` no serviría para nada.
En cuanto a `plazas`, cada `Programa` que se realice puede tener un número de plazas distinto, ya sea porque en fines de semana venga menos gente, etc. Sea como sea, el número de plazas permitidas es un factor externo , por lo que será responsabilidad de quien cree el `Programa` de decidir cuál es el número.

Si no me he explicado bien, lo puedo aclarar.
Ya me dices @fincamd

**Comment by fincamd** [comment]
Hmm... Creo que sé por dónde vas pero creo que lo habíamos pensado para que se pudiese. No obstante tendremos que darle un repaso a todo el diagrama para detectar más problemas de este estilo.

O bien no he entendido el problema concretamente o tienes razón y hay que cambiarlo.

Lo dicho, tendremos que mirarlo con calma

**Comment by AdrianPerezManso** [comment]
Esto se ha resuelto por consecuencia de la resolución de la issue #21.
